services:
  development:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    container_name: legal-toolkit-dev
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - vscode-server:/vscode-server
      - dev-cache:/home/vscode/.cache
      - cargo-cache:/home/vscode/.cargo
      - node-modules:/workspace/node_modules
      - rust-target:/workspace/target
    working_dir: /workspace
    command: sleep infinity
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp}
      - PULSE_RUNTIME_PATH=${PULSE_RUNTIME_PATH:-/tmp/pulse}
      - RUST_LOG=debug
      - TAURI_DEBUG=true
      - NODE_ENV=development
      - PYTHON_ENV=development
    ports:
      - "3000:3000"   # Tauri Dev
      - "5173:5173"   # Svelte Dev
      - "8000:8000"   # FastAPI
      - "1420:1420"   # Tauri IPC
      - "5001:5001"   # IPFS API
      - "4001:4001"   # IPFS Swarm
      - "8080:8080"   # IPFS Gateway
      - "9090:9090"   # Vector DB
    depends_on:
      - postgres
      - redis
      - ipfs
    networks:
      - legal-toolkit-network
    privileged: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  postgres:
    image: postgres:15-alpine
    container_name: legal-toolkit-postgres
    environment:
      POSTGRES_DB: legal_toolkit
      POSTGRES_USER: legal_user
      POSTGRES_PASSWORD: legal_dev_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./web-portal/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - legal-toolkit-network

  redis:
    image: redis:7-alpine
    container_name: legal-toolkit-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - legal-toolkit-network

  ipfs:
    image: ipfs/kubo:latest
    container_name: legal-toolkit-ipfs
    environment:
      - IPFS_PROFILE=server
    volumes:
      - ipfs-data:/data/ipfs
    ports:
      - "4001:4001"     # Swarm port
      - "5001:5001"     # API port
      - "8080:8080"     # Gateway port
    networks:
      - legal-toolkit-network

  vector-db:
    image: qdrant/qdrant:latest
    container_name: legal-toolkit-vectordb
    volumes:
      - vector-data:/qdrant/storage
    ports:
      - "6333:6333"     # HTTP API
      - "6334:6334"     # gRPC API
    networks:
      - legal-toolkit-network

  minio:
    image: minio/minio:latest
    container_name: legal-toolkit-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: legal_admin
      MINIO_ROOT_PASSWORD: legal_dev_storage
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"     # API
      - "9001:9001"     # Console
    networks:
      - legal-toolkit-network

networks:
  legal-toolkit-network:
    driver: bridge

volumes:
  vscode-server:
  dev-cache:
  cargo-cache:
  node-modules:
  rust-target:
  postgres-data:
  redis-data:
  ipfs-data:
  vector-data:
  minio-data: