version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: legal_toolkit
      POSTGRES_USER: legaluser
      POSTGRES_PASSWORD: legalpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://legaluser:legalpass123@postgres:5432/legal_toolkit
      - SECRET_KEY=your-secret-key-change-in-production
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key_here
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: