name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropic/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          review-prompt: |
            Review this pull request for:
            - Security vulnerabilities
            - Code quality and best practices
            - Architecture compliance with legal AI requirements
            - FastAPI and Tauri implementation patterns
            - Database and Docker configuration issues
