name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropics/claude-code-review-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          review-type: "security-focused"
          focus-areas: |
            - Security vulnerabilities and best practices
            - Authentication and authorization implementation
            - Input validation and sanitization
            - Database security and SQL injection prevention
            - API endpoint security
            - Environment variable and secret management
            - CORS configuration
            - Rate limiting implementation
          exclude-patterns: |
            - "*.log"
            - "node_modules/**"
            - "target/**"
            - ".git/**"
            - "**/.env*"

      - name: Run Backend Tests
        working-directory: ./web-portal/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests/ -v

      - name: Security Check
        run: |
          # Check for hardcoded secrets
          if grep -r "sk_live\|pk_live\|whsec_" . --exclude-dir=.git --exclude="*.md" --exclude="*.example"; then
            echo "❌ Production secrets found in code!"
            exit 1
          fi
          
          # Check for .env files in commits
          if git diff --name-only HEAD~1 | grep -E "\.env$"; then
            echo "❌ .env files should not be committed!"
            exit 1
          fi
          
          echo "✅ Basic security checks passed"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Claude Code Review Complete**\n\nSecurity-focused review has been completed. Check the workflow logs for detailed findings and recommendations.'
            })